/* Syllume demo storefront. No real orders, subscriptions, or payments are processed. */
(() => {
  'use strict';
  const products = Array.isArray(window.SYLLUME_PRODUCTS) ? window.SYLLUME_PRODUCTS : [];
  const KEY = 'syllume-demo-cart-v1';
  const formatINR = n => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n)||0);
  const $ = id => document.getElementById(id);
  let cart = loadCart(); let toastTimer;
  const productById = id => products.find(p => p.id === id);
  const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function loadCart(){try{const stored=JSON.parse(localStorage.getItem(KEY)||'[]');if(!Array.isArray(stored))return[];return stored.map(line=>{const p=productById(line.id);if(!p||!p.stock)return null;const q=Math.max(1,Math.min(p.stock,20,Math.floor(Number(line.quantity)||1)));return{id:p.id,quantity:q}}).filter(Boolean)}catch(e){console.warn('Cart unavailable in this browser',e);return[]}}
  function saveCart(){try{localStorage.setItem(KEY,JSON.stringify(cart))}catch(e){console.warn('Could not save local cart',e)}updateCount();renderCart();renderCheckout()}
  function subtotal(){return cart.reduce((sum,l)=>{const p=productById(l.id);return sum+(p?p.price*l.quantity:0)},0)}
  function showToast(message){const el=$('toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2300)}
  function updateCount(){if($('cart-count'))$('cart-count').textContent=String(cart.reduce((s,l)=>s+l.quantity,0))}
  function productCard(p){return `<article class="product-card"><a href="product.html?id=${encodeURIComponent(p.id)}" class="product-link" aria-label="View ${esc(p.name)}"><div class="product-visual"><img src="${esc(p.image)}" alt="${esc(p.alt)}" loading="lazy"><span class="product-badge">${p.sample?'Sample listing':'Available'}</span></div><div class="product-info"><div class="product-line"><h3>${esc(p.name)}</h3><span class="product-price">${formatINR(p.price)}</span></div><p class="product-subtitle">${esc(p.subtitle)}</p><p class="product-notes">${esc(p.notes)} · ${esc(p.size)}</p><span class="stock-note">${p.stock?'Sample stock: '+p.stock:'Out of stock'}</span></div></a><button class="quick-add" type="button" data-add="${esc(p.id)}" ${p.stock?'':'disabled'}>${p.stock?'Add to bag +':'Unavailable'}</button></article>`}
  function drawProducts(items=products){const grid=$('products');if(!grid)return;grid.innerHTML=items.map(productCard).join('');if($('empty-state'))$('empty-state').hidden=items.length>0}
  function filterProducts(){const q=($('search')?.value||'').trim().toLowerCase();const cat=($('category')?.value||'all').toLowerCase();const sort=$('sort')?.value||'featured';let list=products.filter(p=>{const searchable=[p.name,p.subtitle,p.notes,p.description,p.category,...p.tags].join(' ').toLowerCase();return(!q||searchable.includes(q))&&(cat==='all'||p.category.toLowerCase()===cat||p.tags.includes(cat))});if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);if(sort==='popular')list.sort((a,b)=>b.popularity-a.popularity);drawProducts(list)}
  function add(id,qty=1){const p=productById(id);if(!p)return showToast('This product could not be found.');if(p.stock<1)return showToast('This sample product is unavailable.');const q=Math.max(1,Math.min(20,Math.floor(Number(qty)||1)));const line=cart.find(x=>x.id===id);const current=line?line.quantity:0;if(current+q>p.stock)return showToast('That exceeds the sample stock shown.');if(line)line.quantity+=q;else cart.push({id,quantity:q});saveCart();showToast(`${p.name} added to your bag.`)}
  function change(id,delta){const l=cart.find(x=>x.id===id),p=productById(id);if(!l||!p)return;const next=l.quantity+delta;if(next<1)cart=cart.filter(x=>x.id!==id);else if(next<=p.stock&&next<=20)l.quantity=next;else showToast('That exceeds the sample stock shown.');saveCart()}
  function renderCart(){const host=$('cart-lines');if(!host)return;if(!cart.length){host.innerHTML='<div class="cart-empty"><p>Your bag is waiting for a little glow.</p><button type="button" class="button button-dark" data-close-cart>Continue browsing</button></div>'}else{host.innerHTML=cart.map(l=>{const p=productById(l.id);if(!p)return'';return `<article class="cart-item"><img src="${esc(p.image)}" alt=""><div><h3>${esc(p.name)}</h3><p>${formatINR(p.price)} · sample price</p><div class="qty"><button type="button" data-qty="-1" data-id="${esc(p.id)}" aria-label="Decrease quantity">−</button><span>${l.quantity}</span><button type="button" data-qty="1" data-id="${esc(p.id)}" aria-label="Increase quantity">+</button></div><button type="button" class="remove-item" data-remove="${esc(p.id)}">Remove</button></div><strong>${formatINR(p.price*l.quantity)}</strong></article>`}).join('')}if($('subtotal'))$('subtotal').textContent=formatINR(subtotal())}
  function openCart(){const d=$('cart-drawer'),b=$('backdrop');if(!d||!b)return;d.classList.add('open');d.setAttribute('aria-hidden','false');b.hidden=false;document.body.classList.add('locked');$('close-cart')?.focus()}
  function closeCart(){const d=$('cart-drawer'),b=$('backdrop');if(!d||!b)return;d.classList.remove('open');d.setAttribute('aria-hidden','true');b.hidden=true;document.body.classList.remove('locked');$('open-cart')?.focus()}
  function renderFinder(){const form=$('finder-form');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form),scent=String(data.get('scent')||''),occasion=String(data.get('occasion')||''),budget=Number(data.get('budget')||0);let list=products.filter(p=>p.price<=budget);if(scent!=='unscented')list=list.filter(p=>p.tags.includes(scent));if(occasion==='gifting')list.sort((a,b)=>(b.category==='Gift set')-(a.category==='Gift set')||b.popularity-a.popularity);else list.sort((a,b)=>b.popularity-a.popularity);const out=$('finder-result');if(!out)return;const p=list[0];if(!p){out.textContent='No sample listing fits all your choices. Try another fragrance or budget.';return}out.innerHTML=`<div class="match-card"><img src="${esc(p.image)}" alt="${esc(p.alt)}"><div><p class="eyebrow">Your sample match</p><h3>${esc(p.name)}</h3><p>${formatINR(p.price)} · ${esc(p.notes)}</p><a href="product.html?id=${encodeURIComponent(p.id)}">Explore this candle ↗</a></div></div>`})}
  function productDetail(){const host=$('product-detail');if(!host)return;const p=productById(new URLSearchParams(location.search).get('id'));if(!p){host.innerHTML='<div class="not-found"><p class="eyebrow">A little detour</p><h1>We could not find that candle.</h1><a class="button button-dark" href="index.html#shop">Back to the collection</a></div>';return}document.title=`${p.name} — Syllume`;host.innerHTML=`<div class="detail-image"><img src="${esc(p.image)}" alt="${esc(p.alt)}"></div><div class="detail-copy"><p class="eyebrow">Syllume sample collection</p><h1>${esc(p.name)}</h1><p class="detail-price">${formatINR(p.price)} <span class="smallprint">sample price</span></p><p>${esc(p.description)}</p><p><strong>Fragrance notes:</strong> ${esc(p.notes)}</p><p><strong>Size:</strong> ${esc(p.size)}</p><p><strong>Sample stock:</strong> ${p.stock||'Unavailable'}</p><div class="detail-actions"><label class="sr-only" for="detail-qty">Quantity</label><input id="detail-qty" type="number" min="1" max="${Math.min(20,p.stock)}" value="1" ${p.stock?'':'disabled'}><button class="button button-dark" data-detail-add="${esc(p.id)}" type="button" ${p.stock?'':'disabled'}>Add to bag ↗</button></div><div class="content-callout"><strong>Candle safety:</strong> Keep a burning candle in sight and away from children, pets, drafts, and flammable objects. Follow the care instructions verified for your actual product. This sample listing does not certify materials or burn performance.</div><p class="smallprint">Demo listing. Verify all product claims, ingredients, dimensions, stock, and safety guidance before selling.</p></div>`}
  function renderCheckout(){const host=$('checkout-items');if(!host)return;host.innerHTML=cart.length?cart.map(l=>{const p=productById(l.id);return p?`<div class="summary-line"><span>${esc(p.name)} × ${l.quantity}</span><strong>${formatINR(p.price*l.quantity)}</strong></div>`:''}).join(''):'<p>Your bag is empty. Return to the shop to add a sample product.</p>';if($('checkout-subtotal'))$('checkout-subtotal').textContent=formatINR(subtotal());if($('checkout-total'))$('checkout-total').textContent=formatINR(subtotal());if($('checkout-delivery'))$('checkout-delivery').textContent=cart.length?'Not configured':'—'}
  function setupCheckout(){const form=$('checkout-form');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();const msg=$('checkout-message');if(!cart.length){msg.textContent='Your bag is empty. Add a product before continuing.';return}if(!form.reportValidity())return;msg.textContent='Demo only: no order was placed and no payment was taken. Connect a verified payment provider and secure backend before accepting orders.'})}
  function init(){if($('year'))$('year').textContent=new Date().getFullYear();drawProducts();updateCount();renderCart();renderFinder();productDetail();renderCheckout();setupCheckout();$('search')?.addEventListener('input',filterProducts);$('category')?.addEventListener('change',filterProducts);$('sort')?.addEventListener('change',filterProducts);$('open-cart')?.addEventListener('click',openCart);$('close-cart')?.addEventListener('click',closeCart);$('backdrop')?.addEventListener('click',closeCart);$('menu-toggle')?.addEventListener('click',()=>{const nav=$('nav'),btn=$('menu-toggle'),open=nav.classList.toggle('open');btn.setAttribute('aria-expanded',String(open))});$('nav')?.addEventListener('click',e=>{if(e.target.closest('a')){$('nav').classList.remove('open');$('menu-toggle')?.setAttribute('aria-expanded','false')}});document.addEventListener('click',e=>{const a=e.target.closest('[data-add]'),q=e.target.closest('[data-qty]'),r=e.target.closest('[data-remove]'),c=e.target.closest('[data-close-cart]'),d=e.target.closest('[data-detail-add]');if(a)add(a.dataset.add);if(q)change(q.dataset.id,Number(q.dataset.qty));if(r){cart=cart.filter(l=>l.id!==r.dataset.remove);saveCart()}if(c)closeCart();if(d)add(d.dataset.detailAdd,Number($('detail-qty')?.value||1))});$('newsletter-form')?.addEventListener('submit',e=>{e.preventDefault();$('newsletter-message').textContent='Demo form only — no subscription was saved. Connect an email service before launch.'});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeCart()})}
  document.addEventListener('DOMContentLoaded',init);
})();
